version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  
  kafka:
    image: quay.io/debezium/kafka:2.0
    ports:
      - 9092:9092
      - 29092:29092
    links:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
  
  connect:
    image: quay.io/debezium/connect:2.0
    ports:
      - 8083:8083
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  artemis:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161 # Web Console
      - 61616:61616 # Core
      - 5672:5672 # AMQP
      - 61613:61613 # STOMP
      - 1883:1883 # MQTT
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: password
    volumes:
      - ./broker.xml:/var/lib/artemis/etc-override/broker.xml
